"""Frozen independent expected values, never regenerated by the tested engine."""
import hashlib
import json
from decimal import Decimal
from pathlib import Path
import pytest
from app.models.domain import Plans
from app.services.calculation_engine import calculate_kpi
from tests.workbook_fixture import FIXTURE, read_fixture


@pytest.fixture(scope='module')
def reference():
    return json.loads((FIXTURE.parent / 'trofimov_expected.json').read_text(encoding='utf-8'))


@pytest.fixture(scope='module', params=['fixture_adapter', 'production_importer'])
def workbook_result(request):
    if request.param == 'production_importer':
        from app.services.excel_importer import import_excel
        from app.services.mapping_service import ImportSession
        imported = import_excel(FIXTURE)
        assert not imported.errors
        session = ImportSession(imported)
        assert session.validation.pending_mapping_rows == (68, 103, 156, 158)
        for entry in session.mappings:
            if entry.status == 'unresolved':
                session.leave_unmatched(entry.key)
        result = session.calculate(Plans('20000000','10000000','0','0'))
        return imported.shipments, imported.products, result
    shipments, products = read_fixture()
    # Test scenario only. Mandatory plans are not taken from Excel's KPI sheet.
    result = calculate_kpi(shipments, products, Plans('20000000','10000000','0','0'))
    return shipments, products, result


def test_fixture_identity_and_population(reference, workbook_result):
    shipments, products, result = workbook_result
    assert hashlib.sha256(FIXTURE.read_bytes()).hexdigest() == reference['fixture_sha256']
    assert len(shipments) == reference['shipments'] == 170
    assert len(products) == reference['products'] == 28
    assert len(result.included_rows) == reference['included_count'] == 64
    assert len(result.excluded_rows) == 106


@pytest.mark.parametrize('quarter', [1, 2, 3, 4])
def test_exact_quarter_totals_and_drilldown(reference, workbook_result, quarter):
    result = workbook_result[2]
    q = result.quarters[quarter-1]
    key = str(quarter)
    assert q.actual == Decimal(reference['quarter_actuals'][key])
    assert q.calculated_premium == Decimal(reference['quarter_premiums'][key])
    assert list(q.actual_source_rows) == reference['actual_source_rows'][key]
    assert [b.base for b in q.blocks] == [Decimal(v) for v in reference['block_bases'][key]]
    assert [list(b.source_rows) for b in q.blocks] == reference['block_source_rows'][key]
    for b in q.blocks:
        assert b.premium == b.base * b.rate
        assert sum((a.shipment.revenue for a in result.audit if a.shipment.source_row in b.source_rows), Decimal(0)) == b.base


def test_every_source_row_matches_frozen_audit(reference, workbook_result):
    result = workbook_result[2]
    actual = [dict(source_row=a.shipment.source_row, eligible=a.eligible,
                   reason=a.exclusion_reason, category=a.product.category if a.product else None,
                   canonical_name=a.product.canonical_name if a.product else None, block=a.block,
                   **{field: str(getattr(a, field)) if getattr(a, field) is not None else None
                      for field in ('actual_price_raw', 'actual_price_rounded',
                                    'threshold_raw', 'threshold_rounded', 'price_delta')})
              for a in result.audit]
    assert actual == reference['audit']
    for key, amount in result.green_totals.items():
        assert amount == Decimal(reference['green_totals'].get('|'.join(map(str,key)), '0'))


def test_manual_plans_and_annual_recovery(workbook_result):
    result = workbook_result[2]
    assert result.plans.annual == Decimal('30000000')
    assert result.annual_actual == Decimal('28473035.803325146570')
    assert result.annual_pass
    assert result.quarters[0].payable == 0
    assert result.quarters[1].payable == Decimal('139195.4719100000090')
    assert result.quarters[3].payable == Decimal('112087.8452000000000')
    assert result.annual_payable == Decimal('251283.3171100000090')


def test_high_manual_plans_block_payment(workbook_result):
    shipments, products, _ = workbook_result
    result = calculate_kpi(shipments, products, Plans('20000000','15000000','1000000','1000000'))
    assert not result.annual_pass
    assert all(q.payable == 0 for q in result.quarters)
    assert result.annual_calculated_premium == Decimal('251283.3171100000090')


def test_unmatched_fixture_rows_still_count(workbook_result):
    result = workbook_result[2]
    unknown = [a for a in result.excluded_rows if a.product is None]
    assert [a.shipment.source_row for a in unknown] == [68, 103, 156, 158]
    assert all(a.shipment.source_row in result.quarters[a.quarter-1].actual_source_rows for a in unknown)
    assert all(a.block is None for a in unknown)
